apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-vm
  labels:
    app: ubuntu-vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        app: ubuntu-vm
        kubevirt.io/domain: ubuntu-vm
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:24.04
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              users:
                # Keep the default user provided by the Ubuntu cloud image.
                - default
                # Create an additional user named "ubuntu".
                - name: praveen
                  # Add the user to the administrative and sudo groups.
                  groups: [adm, sudo]
                  # Use Bash as the user's login shell.
                  shell: /bin/bash
                  # Password login allowed
                  lock_passwd: false
              chpasswd:
                users:
                  - name: praveen
                    password: "12345678"
                    type: text
                expire: false
              ssh_pwauth: true
              packages:
                - openssh-server
              write_files:
                - path: /etc/ssh/sshd_config.d/60-cloud-init-password-auth.conf
                  permissions: "0644"
                  content: |
                    PasswordAuthentication yes
              runcmd:
                - systemctl enable ssh
                - systemctl restart ssh
