{{- if and .Values.storage.enabled (not .Values.storage.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  {{- with .Values.storage.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
