apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-backend
  template:
    metadata:
      labels:
        app: hello-backend
    spec:
      containers:
        - name: hello-backend
          image: traefik/whoami
          ports:
            - containerPort: 80